### ISSUE TITLE
not working examples for bare-browser and esbuild-browser

### ISSUE THREAD

**Issue by uros87** [duckdb/duckdb-wasm#438] opened 2021-11-30 19:12 UTC
when I try to run examples for those two projects ( bare-browser and esbuild-browser), I get errors. I cloned whole project and tried to run it.
Can someone give more info about it?

Also, can someone point me to working example for react and vanilla JS front-end project?

**Comment by Alex-Monahan** [comment] 2021-11-30 19:23
Thanks for giving it a try! What errors are you getting? What environment are you working in?

**Comment by ankoh** [comment] 2021-11-30 19:26
The examples are built with our CI and should work.
But they currently expect that the wasm modules are compiled within the project which is a little bit involved.

E.g. the bare browser example copies the wasm modules here:
https://github.com/duckdb/duckdb-wasm/blob/2a24868a42261f2345b4ea8857f1328eb26e5275/examples/bare-browser/bundle.mjs#L8-L13.
You'd have to point this to something like `./node_modules/@duckdb/duckdb-wasm/dist` instead.

**Comment by ankoh** [comment] 2021-11-30 19:28
We could maybe make the examples independent of the monorepo at some point.

**Comment by uros87** [comment] 2021-11-30 19:45
Hey Alex and ankoh thanks for answering.
I get:
GET http://127.0.0.1:8080/duckdb-browser.mjs net::ERR_ABORTED 404 (Not Found),
when i run examples.

@Alex-Monahan 
I'm running in Ubuntu 18.04 if you mean env by that.

@ankoh
when i changed this line of code with this I still get the same error

![Screenshot from 2021-11-30 20-42-14](https://user-images.githubusercontent.com/40358084/144116901-66a682b8-b686-4eab-84fc-f2917ad64479.png)

**Comment by ankoh** [comment] 2021-11-30 19:46
You are still running the example in the monorepo. Copy the example folder out of the monorepo yarn workspace, fix the path and run npm install in the example folder.

**Comment by ankoh** [comment] 2021-11-30 19:56
Ah alternatively, you can do the following to run the examples in the monorepo:
1. Clone the repo
2. Run `yarn install`
3. Run `./scripts/npm_restore.sh 1.11.1-dev54.0`
4. Run `make examples`

**Comment by ankoh** [comment] 2021-11-30 19:57
This will copy the published dist folder from npm.

**Comment by ankoh** [comment] 2021-12-01 06:54
Closing this for now since this works as intended. We could track react examples in a dedicated issue.

**Closed** 2021-12-01 06:55 UTC

**Comment by uros87** [comment] 2021-12-01 15:43
Thanks ankoh on thorough answers.
But I don't have a success to run example for bare-browser in isolation, though i successfully ran example in mono repo. 

I've followed your instructions and i get

![Screenshot from 2021-12-01 16-41-44](https://user-images.githubusercontent.com/40358084/144265432-1c03fdf3-437d-428e-9217-d8c6bcb18034.png)

**Comment by ankoh** [comment] 2021-12-01 15:51
Did you install version 1.11.1-dev54.0 in the package.json?

**Comment by uros87** [comment] 2021-12-01 16:04
"@duckdb/duckdb-wasm": "1.11.1-dev54.0"
   "@duckdb/duckdb-wasm": "^1.11.0"
   
I have tried with both of these versions, but I get the same error.
