### ISSUE TITLE
Prepared statement does not support unicode values

### ISSUE THREAD

**Issue by kaciakmaciak** [duckdb/duckdb-wasm#1813] opened 2024-08-13 11:07 UTC
### What happens?

Prepared insert statement does not support passing values with unicode characters defined using `\u`. Anything after such character is escaped.

### To Reproduce

```ts
const conn = await db.connect();
await conn.query(`
  CREATE TABLE "Test" (value VARCHAR)
`);
const stmt = await conn.prepare(`
  INSERT INTO "Test" (value)
  VALUES (?)
`);
await stmt.query('🦆🦆🦆🦆🦆');
await stmt.query('goo␀se');
await stmt.query('goo\u0000se');
const result = await conn.query(`
  SELECT * FROM "Test"
`);
console.log(result.toArray().map((item) => item.toJSON()));  // Returns '🦆🦆🦆🦆🦆', 'goo␀se', 'goo'
```

Please see an example in [Codesandbox](https://codesandbox.io/p/sandbox/zen-cloud-yxz3fs?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzsag87t00063d5r4v7s11b8%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzsag87t00023d5roq95hyn8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzsag87t00033d5rtcknfb04%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzsag87t00053d5rm0dstlkm%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzsag87t00023d5roq95hyn8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzsag87s00013d5rzbzhskt7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clzsag87t00023d5roq95hyn8%2522%252C%2522activeTabId%2522%253A%2522clzsag87s00013d5rzbzhskt7%2522%257D%252C%2522clzsag87t00053d5rm0dstlkm%2522%253A%257B%2522id%2522%253A%2522clzsag87t00053d5rm0dstlkm%2522%252C%2522activeTabId%2522%253A%2522clzsaggut000u3d5ru1ieq3l0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzsag87t00043d5rnw5kfl4m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzsaggut000u3d5ru1ieq3l0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzsag87t00033d5rtcknfb04%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzsag87t00033d5rtcknfb04%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

### Browser/Environment:

Any

### Device:

Any

### DuckDB-Wasm Version:

1.28.1-dev248.0

### DuckDB-Wasm Deployment:

N/A

### Full Name:

Katarina Anton

### Affiliation:

individual

**Comment by carlopi** [comment] 2024-08-21 14:36
Thanks for raising this, problem here is connected to usage of the JSON.stringify while going from JS object to a representation more closely related to C++, that is basically `char a[]`.

In particular we use `JSON.stringify`, that is not information preserving.

Solution here might involve re-implementing JSON.stringify, not really looking forward to, but I don't see another way out

**Comment by carlopi** [comment] 2024-08-22 08:16
I fixed this in https://github.com/duckdb/duckdb-wasm/pull/1823.

There will still a problem open: going through the native JS-api means strings are treated as JavaScript Strings (and not as Uint8Array, that closely match char* C++ semantics), as such some normalisations are performed, and for example `goo\u0000se` will be normalised to `goo\x00se`.

I am not 100% happy with the fix, but it's hard to say what is the intended semantic (and a solid implementation) for it. This is a more general problem, shared with Python and node.js bindings.

Escaping the backslash with another `\` will have those be kept as intended.

Note that going through SQL (eg. the duckdb-wasm shell) this is working as intended.

I am inclined to consider this as solved.

**Comment by carlopi** [comment] 2024-08-22 08:16
I will close the issue for now, but feel free to comment / reopen if this is not satisfactory.

**Closed by carlopi** 2024-08-22 08:16 UTC
Labels: reproduced

**Comment by kaciakmaciak** [comment] 2024-08-22 09:09
Thanks heaps for a quick fix 👍
